### PR TITLE
Codename One Property cross demo

### PR DESCRIPTION
**Pull request by codenameone**
This is a clean room implementation of the spec (not based on existing code).

### CODE REVIEW

**Comment by codenameone** [comment]
Is there a reason this pull request wasn't merged?
It's pretty old by now and there is a newer version [here](https://github.com/codenameone/PropertyCross/). I can work on submitting that but it would be silly if it would just sit here for a year...

**Comment by codenameone** [comment]
@ColinEberhardt any chance of ever merging this?
Noticed you just merged a different PR.

**Comment by codenameone** [comment]
FYI there is a much newer version of this by now https://www.codenameone.com/blog/property-cross-revisited.html

**Comment by ColinEberhardt** [comment]
Sorry it's taken a long time to merge this, it's been a struggle to find the time to maintain this project! If be happy to receive a pull request that updates his code to the latest.

**Comment by ColinEberhardt** [comment]
Would it be possible for you to add a read me that follows this outline:

https://github.com/tastejs/PropertyCross/blob/master/jquerymobile/README.md

It makes it much easier for people to understand your demo.

**Comment by codenameone** [comment]
Sure, building a new pull request now.
Thanks!

**Comment by codenameone** [comment]
Done https://github.com/tastejs/PropertyCross/pull/335

**Pull request merged**
