### PR TITLE
Add PropertyCross implementation using Intersoft Crosslight framework

### PR DESCRIPTION
**Pull request by jimmyps**
Feature-complete and polished implementation of PropertyCross using Crosslight. All code have been reviewed and passed build in all platforms, tested to work perfectly with both simulators and devices.

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Hi @jimmyps thanks for the submission, it all looks in very good order :-)

The one thing I would like to tweak a bit is your README file. Our preference is that these are matter-of-fact, and avoid any sales 'spin'! Yours isn't too bad, but needs a bit of work.

I'd like to suggest the following:

"[Crosslight](http://www.intersoftpt.com/Crosslight/) is a commercial cross-platform mobile development toolset from Intersoft which is geared towards enterprise app development. With Crosslight you use an extensible MVVM architecture and the Xamarin platform to build native iOS, Android and Windows Phone applications from a common codebase.

The Crosslight Foundation provides a set of APIs that support application development, these include a cross-platform binding framework (adding binding to iOS and Android), an Entity Designer for data models, a cross-platform navigation model and presenter services. As a result, Crosslight applications allow you to share more code between platforms than a Xamarin equivalent."

I've removed works like 'advanced' and 'highest level of code sharing', and replaced it with more facts and something which I feel is a better descriptions of what Crosslight actually is!

People who use PropertyCross will want to know how Crosslight differs from similar implementations like Xamarin, and MvvmCross. We aim to give them the facts!

**Comment by jimmyps** [comment]
@ColinEberhardt Thanks for your suggestion on the README revision. I agree with your edits which depict a much natural description of Crosslight :) I have pushed the revision to the pull request. 

Let me know if you have further feedback.

**Comment by ColinEberhardt** [comment]
Great - thanks for incorporating these changes. Time to merge :-) I'll add crosslight to the website shortly.

**Comment by jimmyps** [comment]
Thanks! Looking forward to the Crosslight addition in the website.

**Comment by jimmyps** [comment]
@ColinEberhardt Any news on the website update to include Crosslight? Many thanks!

**Comment by ColinEberhardt** [comment]
@jimmyps - it's coming soon, I like to batch up a few changes and update all in one go.

**Comment by nicholaslie90** [comment]
Hi @ColinEberhardt, any updates to Crosslight addition reference to the website?

**Comment by bdimitrov-SL** [comment]
Hi @jimmyps - I am currently working on adding Crosslight to the website, but I ran into some problems with the Android version. Whenever I try to search for properties I get 403 Forbidden result from the Nestoria API. On further investigation I found out that the API expects a User-Agent header in the request, otherwise it always returns 403. So I tried to modify the code to include User-Agent, but nothing I tried worked. After going through the API documentation here's a list of things I tried in <code>PropertyRepository.cs</code>:
- Setting UserAgent property of RestClient
- AddDefaultHeader method of RestClient
- AddDefaultParameter method of RestClient
- AddHeader method of the RestRequest object
- AddParameter method of RestRequest object

For all of the above I either get a 'Network is unreachable error' or the User-Agent is still not set in the actual request. Do you have any idea if there is another way to set the User-Agent header in Crosslight?

**Comment by jimmyps** [comment]
Hi @bdimitrov-SL, thanks for reaching out.

By default, the .NET implementation of HttpRequest doesn’t allow setting user-agent, so that’s the cause of the “Unreachable error”. The correct way to set UserAgent is by setting the RestClient.UserAgent property. However, there was an issue with the existing Crosslight version where the user agent isn’t properly carried out to the actual request. This has been fixed in the latest Crosslight which we will update to GitHub tomorrow.

In addition, tomorrow’s update will also include a brand-new Android Material version of PropertyCross based on Crosslight 5.

Best,
Jimmy

**Comment by bdimitrov-SL** [comment]
@jimmyps thank you for the fast response. In this case I'll go ahead and add the Crosslight info page to the website and you can raise a new pull request with the updated Android Material version of the app whenever you are ready.

Cheers,
Bogdan

**Comment by jimmyps** [comment]
@bdimitrov-SL sure, please inform when Crosslight has been added to the website.

FYI, here’s the pull request:

https://github.com/tastejs/PropertyCross/pull/325 <https://github.com/tastejs/PropertyCross/pull/325>

I’ve also updated our developer center with the latest information on this update: http://developer.intersoftsolutions.com/display/crosslight/PropertyCross+Sample <http://developer.intersoftsolutions.com/display/crosslight/PropertyCross+Sample> 

Let me know if you have any questions.

Thanks,
Jimmy

**Comment by bdimitrov-SL** [comment]
@jimmyps The Crosslight page has been added to the website:
http://propertycross.com/crosslight/

Cheers,
Bogdan

**Comment by jimmyps** [comment]
@bdimitrov-SL Thanks! However, I noticed one issue, the Windows platform is not ticked in both home page and the Crosslight page. Crosslight supports Windows Phone 8 and Windows 8. The PropertyCross itself has the Windows Phone version, can check it out [here](https://github.com/tastejs/PropertyCross/tree/master/crosslight/PropertyCross_Intersoft.WinPhone).

Please inform when it's updated. Thanks!

**Comment by ColinEberhardt** [comment]
Hi @jimmyps - we're actually in the process of removing Windows Phone from the website. When we initially started out on PropertyCross the market share was growing and the platform showed promise. However now it's not looking so good! The market share is very low and showing no signs of improving.

In our website update (coming soon), we'll remove the Windows Phone 'icons' and screenshots. 

We'd happy to mention Windows Phone support (and BlackBerry etc ...) in the description text for any framework that offers that as a feature.

**Comment by jimmyps** [comment]
Got it, thanks for the clarification.

One more thing, can you help to add Android Material screenshots from this page? http://developer.intersoftsolutions.com/display/crosslight/PropertyCross+Sample

Thanks,
Jimmy

**Comment by AlexanderGrant1** [comment]
Hello @jimmyps.

I've just tried to build the Android Material Design version of Crosslight and I'm getting an error that relates to the 'ConvertResourcesCases' task failing 'unexpectedly'. The root of the problem appears to be an issue relating to the character length of my MSBuild install location. I've been unable to find a way of stopping this task from running and I wonder whether you would be able to do a build for us in order to produce an apk file? I plan to get an iOS build for Crosslight done at some point next week. Your help is greatly appreciated.

**Comment by jimmyps** [comment]
@AlexanderGrant1 Sure thing, here you go: https://drive.google.com/open?id=0B_cux9eX2CY9U2R3TmE3bU0teG8

Let me know if you need the iOS build as well. Thanks!

**Comment by AlexanderGrant1** [comment]
Thanks for the that! If you could also provide me with an iOS build that would be great.

**Comment by AlexanderGrant1** [comment]
Hi @jimmyps. I'm just wondering whether you got round to producing the iOS build?

**Comment by jimmyps** [comment]
Hi Alex, sorry for the delay, it has been a busy week. I’ll send you the iOS build tomorrow.

**Comment by jimmyps** [comment]
@AlexanderGrant1 here you go: https://drive.google.com/file/d/0B_cux9eX2CY9ajd4S3hhUnhBbGc/view?usp=sharing

Let me know when everything's up in your website. Thanks!

**Pull request merged**
