### PR TITLE
PropertyCross v2

### PR DESCRIPTION
**Pull request by jimmyps**
- Updated to Crosslight 5.0 (build 499).
- Updated core project to PCL Profile 78.
- Added PropertyCross for Android Material, featuring brand-new
Crosslight Material theme, shared element transitions, collapsing
toolbar, parallax image, and floating action button.
- Updated iOS project to target version 9.2, featuring full storyboard
support.
- Added UserAgent to comply with Nestoria's API requirement.
- All projects are updated to use Crosslight NuGet packages.

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Many thanks for the update. I'm happy to merge this in, but before I do so, can I please ask you to update the README? Just a couple of minor points, can you add an 'Application Structure' section. See this example:

https://github.com/tastejs/PropertyCross/tree/master/jquerymobile#application-structure

This really helps people find their way around the application.

Also, can you please remove the copyright (I should have spotted this first time round!), this project is open source and MIT licensed. I hope that is OK with you?

@bdimitrov-SL - can you please help with getting Crosslight added to the website?

**Comment by jimmyps** [comment]
@ColinEberhardt Sure, no problems. Updated the README file as requested. Let me know if you have any other feedback. Thanks!

**Comment by ColinEberhardt** [comment]
Thanks for the update :-)

**Comment by jimmyps** [comment]
Thanks @ColinEberhardt. Any estimation when Crosslight can be added to the website?

**Comment by bdimitrov-SL** [comment]
@jimmyps I'll raise a pull request for the initial version of the Crosslight post sometime today - the only thing it will be missing is the download links. I'll add those to the post in the beginning of next week after I've built and tested the new code.

Cheers,
Bogdan

**Pull request merged**
