### PR TITLE
PropertyCross with V-Play Apps

### PR DESCRIPTION
**Pull request by alexleutgoeb**
As discussed in #323 here is the PR for the V-Play Apps implementation. Please let me know if any changes are required.

Many thanks,
Alex

### CODE REVIEW

**Comment by alexleutgoeb** [comment]
Just wanted to follow up if there is anything missing in the pull request? Many thanks!

**Comment by ColinEberhardt** [comment]
Hi - sorry for the delay, just getting back to some PropertyCross pull requests. Is this one still good to go?

**Comment by alexleutgoeb** [comment]
Hi @ColinEberhardt, thanks for getting back. This should still be good to go if there are no changes were made for the project definition itself. Thanks!

**Comment by ColinEberhardt** [comment]
Great - thanks.

**Comment by ColinEberhardt** [comment]
Now that it's merged, we need to get it on the website. You can see a recent Pull Request for updating the site here:

https://github.com/ColinEberhardt/PropertyCross-Site/pull/28

Would you be OK to give this a try?

**Comment by alexleutgoeb** [comment]
Sure, I will keep you updated on this, thanks!

**Pull request merged**
