### PR TITLE
PropertyCross in Qt

### PR DESCRIPTION
**Pull request by Deadolus**
# This is a port of the PropertyCross application in Qt using Qml. 
The app runs without errors on all platforms. 

We didn't style the Buttons and other Widgets on the other Platforms to look native - we rather expected Qt to do this on its own. 
But it seems that Qt isn't looking very native on all platforms except Android - in fact everything looks very similar to Android. 
In the code we are show casing a way in which interested parties could further style the App with own (more native-looking) Qml-Types (see AppStyle.qml Singleton for this) - we so far only changed the Title color of the App depending on the platform the app is running on.

While we had the app running on Windows - **we currently lack pictures of the App in Windows Phone** - we hope to add them shortly - but other parties may wish to add them sooner.

Please let us know if you need anything more from us. 

We hope to have solved issue https://github.com/tastejs/PropertyCross/issues/59 with this pull request

This code is provided by BBV Software Solutions AG - www.bbv.ch - as is, without any warranties, as Open Source 

## Android Screenshots
screenshot_2015-08-14-15-55-03
screenshot_2015-08-14-15-55-12
screenshot_2015-08-14-15-55-18
screenshot_2015-08-14-15-55-24

## Ios Screenshots
ios simulator screen shot 14 aug 2015 13 46 33
ios simulator screen shot 14 aug 2015 13 47 32
ios simulator screen shot 14 aug 2015 13 47 38
ios simulator screen shot 14 aug 2015 13 48 12

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
That's awesome, thanks @Deadolus - before I merge can you add a README? They all follow the same rough template. The KendoUI is probably a good one to follow:

https://github.com/tastejs/PropertyCross/blob/master/kendoui/README.md

Thanks.

**Comment by Deadolus** [comment]
I added the README to the Qt-directory.

**Comment by ColinEberhardt** [comment]
Hi @Deadolus - sorry for the slow response, thanks for the update :-)

**Comment by ColinEberhardt** [comment]
I'll add this to the website on our next update, although feel free to add a PR with the additions:

https://github.com/ColinEberhardt/PropertyCross-Site

**Pull request merged**
