### PR TITLE
Xenarius implementation

### PR DESCRIPTION
**Pull request by chebum**
Added an implementation made with Xenarius - mobile app builder.

The folder contains app-conf.xapp file with full app description. For convenience I added a cordova app template. You can build it either using command line interface or PhoneGap build service.

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Hi - sorry for the delay, just getting back to some PropertyCross pull requests. Is this one still good to go?

**Comment by chebum** [comment]
Hi @ColinEberhardt Thank you for looking into this. We updated the project file. It's fully correct now.

**Comment by chebum** [comment]
@ColinEberhardt thank you for the merge. Do you need anything from us to let us appear on the propertycross website?

**Comment by ColinEberhardt** [comment]
Hi @chebum - the website is built from a separate github project. You can see a recent pull request that added codenameone here:

https://github.com/ColinEberhardt/PropertyCross-Site/pull/28

If you'd like to try and create a suitable pull request that would be great. The main thing you need to do is create the required screenshots. I can fix up any issues if you have problems building / testing the website. Thanks :-)

**Pull request merged**
